/**
 * @module @kb-labs/mind-cli/errors/error-codes
 * Centralized error codes for Mind plugin
 */

/**
 * Error codes used in Mind plugin commands
 */
export const MIND_ERROR_CODES = {
    // RAG errors
    RAG_QUERY_FAILED: 'MIND_RAG_QUERY_FAILED',
    RAG_QUERY_MISSING_TEXT: 'MIND_RAG_QUERY_MISSING_TEXT',
    RAG_INDEX_FAILED: 'MIND_RAG_INDEX_FAILED',
    RAG_SCOPE_NOT_FOUND: 'MIND_RAG_SCOPE_NOT_FOUND',
    
    // Sync errors
    SYNC_FAILED: 'MIND_SYNC_FAILED',
    SYNC_ADD_FAILED: 'MIND_SYNC_ADD_FAILED',
    SYNC_UPDATE_FAILED: 'MIND_SYNC_UPDATE_FAILED',
    SYNC_DELETE_FAILED: 'MIND_SYNC_DELETE_FAILED',
    SYNC_MISSING_FLAGS: 'MIND_SYNC_MISSING_FLAGS',
    SYNC_MISSING_CONTENT: 'MIND_SYNC_MISSING_CONTENT',
    SYNC_RESTORE_FAILED: 'MIND_SYNC_RESTORE_FAILED',
    SYNC_CLEANUP_FAILED: 'MIND_SYNC_CLEANUP_FAILED',
    
    // Query errors
    QUERY_INVALID_NAME: 'MIND_QUERY_INVALID_NAME',
    QUERY_MISSING_FLAGS: 'MIND_QUERY_MISSING_FLAGS',
    QUERY_MISSING_FILE: 'MIND_QUERY_MISSING_FILE',
    QUERY_MISSING_PATH: 'MIND_QUERY_MISSING_PATH',
    QUERY_EXECUTION_FAILED: 'MIND_QUERY_EXECUTION_FAILED',
    
    // Feed errors
    FEED_FAILED: 'MIND_FEED_FAILED',
    FEED_INVALID_SOURCE: 'MIND_FEED_INVALID_SOURCE',
    FEED_MISSING_SOURCE: 'MIND_FEED_MISSING_SOURCE',
    
    // Pack errors
    PACK_FAILED: 'MIND_PACK_FAILED',
    PACK_MISSING_SOURCE: 'MIND_PACK_MISSING_SOURCE',
    
    // Verify errors
    VERIFY_FAILED: 'MIND_VERIFY_FAILED',
    
    // Init errors
    INIT_FAILED: 'MIND_INIT_FAILED',
    INIT_ALREADY_INITIALIZED: 'MIND_INIT_ALREADY_INITIALIZED',
} as const;

export type MindErrorCode = typeof MIND_ERROR_CODES[keyof typeof MIND_ERROR_CODES];

