import type { PluginContracts } from './types';
import { contractsSchemaId, contractsVersion } from './version';

export const pluginContractsManifest: PluginContracts = {
  schema: contractsSchemaId,
  pluginId: '@kb-labs/mind',
  contractsVersion,
  artifacts: {
    'mind.pack.output': {
      id: 'mind.pack.output',
      kind: 'markdown',
      description: 'Markdown context pack generated by mind:pack and mind:feed commands.',
      pathPattern: '.kb/mind/pack/{profile}/{runId}.md',
      mediaType: 'text/markdown',
      example: {
        summary: 'Context pack sample for a repository intent',
        payload: '# Project Context\n\n- Packages: mind-cli, mind-pack\n- Components: query orchestrator, pack builder',
      },
    },
    'mind.query.output': {
      id: 'mind.query.output',
      kind: 'file',
      description: 'Serialized query output emitted in TOON format.',
      pathPattern: '.kb/mind/query/{profile}/{runId}.toon',
      mediaType: 'application/x-toon',
      schemaRef: '@kb-labs/mind-contracts/schema#MindQueryCommandOutputSchema',
    },
    'mind.update.report': {
      id: 'mind.update.report',
      kind: 'json',
      description: 'JSON summary emitted by mind:update and mind:feed when run with --json.',
      schemaRef: '@kb-labs/mind-contracts/schema#MindUpdateCommandOutputSchema',
    },
  },
  commands: {
    'mind:init': {
      id: 'mind:init',
      description: 'Initialise the Mind workspace structure.',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindInitCommandInputSchema',
        format: 'zod',
      },
      examples: ['kb mind init --force', 'kb mind init --json'],
    },
    'mind:update': {
      id: 'mind:update',
      description: 'Update dependency and API indexes for the current workspace.',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindUpdateCommandInputSchema',
        format: 'zod',
      },
      output: {
        ref: '@kb-labs/mind-contracts/schema#MindUpdateCommandOutputSchema',
        format: 'zod',
      },
      produces: ['mind.update.report'],
      examples: ['kb mind update', 'kb mind update --since HEAD~1 --json'],
    },
    'mind:pack': {
      id: 'mind:pack',
      description: 'Build a Markdown knowledge pack for AI workflows.',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindPackCommandInputSchema',
        format: 'zod',
      },
      output: {
        ref: '@kb-labs/mind-contracts/schema#MindPackCommandOutputSchema',
        format: 'zod',
      },
      produces: ['mind.pack.output'],
      examples: ['kb mind pack --intent "summarise repository"', 'kb mind pack --intent "review" --json'],
    },
    'mind:feed': {
      id: 'mind:feed',
      description: 'Run update (optional) and pack in a single command optimised for AI assistants.',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindFeedCommandInputSchema',
        format: 'zod',
      },
      output: {
        ref: '@kb-labs/mind-contracts/schema#MindFeedCommandOutputSchema',
        format: 'zod',
      },
      produces: ['mind.pack.output', 'mind.update.report'],
      examples: ['kb mind feed --intent "pair programming"', 'kb mind feed --intent "hotfix" --no-update --json'],
    },
    'mind:query': {
      id: 'mind:query',
      description: 'Inspect indexed repository data (impact, externals, docs, meta, and more).',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindQueryCommandInputSchema',
        format: 'zod',
      },
      output: {
        ref: '@kb-labs/mind-contracts/schema#MindQueryCommandOutputSchema',
        format: 'zod',
      },
      produces: ['mind.query.output'],
      examples: ['kb mind query externals --json', 'kb mind query impact --file src/index.ts --toon'],
    },
    'mind:verify': {
      id: 'mind:verify',
      description: 'Validate Mind indexes and surface inconsistencies.',
      input: {
        ref: '@kb-labs/mind-contracts/schema#MindVerifyCommandInputSchema',
        format: 'zod',
      },
      output: {
        ref: '@kb-labs/mind-contracts/schema#MindVerifyCommandOutputSchema',
        format: 'zod',
      },
      examples: ['kb mind verify', 'kb mind verify --json'],
    },
  },
  workflows: {
    'mind.workflow.feed': {
      id: 'mind.workflow.feed',
      description: 'One-shot workflow orchestrating update (optional) followed by pack generation.',
      produces: ['mind.pack.output'],
      steps: [
        {
          id: 'mind.workflow.feed.update',
          commandId: 'mind:update',
          produces: ['mind.update.report'],
        },
        {
          id: 'mind.workflow.feed.pack',
          commandId: 'mind:pack',
          produces: ['mind.pack.output'],
        },
      ],
    },
  },
  api: {
    rest: {
      basePath: '/v1/plugins/mind',
      routes: {
        'mind.rest.query': {
          id: 'mind.rest.query',
          method: 'POST',
          path: '/query',
          description: 'Execute a Mind query and return structured sections for Studio.',
          request: {
            ref: '@kb-labs/mind-contracts/schema#MindQueryRequestSchema',
            format: 'zod',
          },
          response: {
            ref: '@kb-labs/mind-contracts/schema#MindQueryResponseSchema',
            format: 'zod',
          },
          produces: ['mind.query.output'],
        },
        'mind.rest.verify': {
          id: 'mind.rest.verify',
          method: 'GET',
          path: '/verify',
          description: 'Summarise index verification status for Studio dashboards.',
          response: {
            ref: '@kb-labs/mind-contracts/schema#MindVerifyResponseSchema',
            format: 'zod',
          },
        },
      },
    },
  },
};
